from pathlib import Path
import json, textwrap
ROOT=Path(__file__).resolve().parents[1]
def md(s): return {'cell_type':'markdown','metadata':{},'source':textwrap.dedent(s).strip()+'\n'}
def code(s): return {'cell_type':'code','metadata':{},'execution_count':None,'outputs':[],'source':textwrap.dedent(s).strip()+'\n'}
BOOT='''
from pathlib import Path
import sys, os
# В Colab загрузите архив KandinskyLab-colab.zip через панель Files и распакуйте
# ячейкой из README. Здесь ищем корень курса, не меняя рабочую директорию.
candidates=[Path.cwd(), *Path.cwd().parents, Path('/content/KandinskyLab')]
ROOT=next((p for p in candidates if (p/'labkit').is_dir()), None)
if ROOT is None: raise RuntimeError('Сначала распакуйте архив курса; инструкции в README.')
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
os.environ.setdefault('MPLCONFIGDIR',str(ROOT/'artifacts/matplotlib'))
import torch, numpy as np, matplotlib.pyplot as plt
from labkit.common import SOURCE, REVISION, device_info, source_excerpt, release, shifted_schedule
# Маленькие эксперименты по умолчанию CPU: быстро и одинаково в Mac/Colab.
# Для отдельной проверки Metal смените LAB_DEVICE на mps.
LAB_DEVICE='cpu'
torch.manual_seed(42)
torch.set_num_threads(2)
print(device_info())
'''
END='''
### Проверьте понимание

Не меняйте сразу несколько параметров. Сначала сформулируйте гипотезу, затем измените один параметр и сравните результат с исходным. Запишите: что было входом, что стало выходом, какие размеры изменились и почему.

Учебные модели со случайными весами показывают **механизм**, но не качество Kandinsky. Тяжёлые эксперименты запускаются только при включении соответствующего флага; пропуск этих ячеек не означает успешный запуск настоящих весов.
'''
def write(name,title,intro,sections):
 cells=[md('# '+title+'\n\n'+intro),md('### Перед началом\n\nЗапускайте ячейки сверху вниз. Для каждой операции сначала прочитайте пояснение, затем выполните код и сравните вывод с ожидаемым. Установка описана в README; сетевых загрузок в учебном режиме нет.'),code(BOOT)]
 for s in sections: cells.append(md(s[0])); cells.append(code(s[1])) if len(s)>1 else None
 cells.append(md(END))
 nb={'nbformat':4,'nbformat_minor':5,'metadata':{'kernelspec':{'display_name':'Python 3 (KandinskyLab)','language':'python','name':'python3'},'language_info':{'name':'python','version':'3.12'},'colab':{'name':name,'provenance':[]}},'cells':cells}
 for i,c in enumerate(cells): c['id']=f'cell-{i:03}'
 (ROOT/'notebooks'/name).write_text(json.dumps(nb,ensure_ascii=False,indent=1))

write('00_start_and_training_map.ipynb','00. От промпта к видео: карта и ресурсы','Цель: понять роли всех компонентов до загрузки весов. Итоговый ориентир — T2V Lite distilled16steps 5s; учебный режим работает на M3 Max и в CPU Colab.',[
('### 1. Модель — это система\n\nПредставьте фильм как маршрут: текст задаёт пункт назначения, VAE определяет язык компактных кадров, DiT подсказывает движение, sampler делает шаги. Токенизатор преобразует строку в номера; текстовый энкодер преобразует номера в векторы. Они решают разные задачи.', "from labkit.components import REPOS\nfor component,repo in REPOS.items(): print(component, '→', repo)"),
('### 2. Читаем настоящий рецепт\n\nYAML не содержит веса: это размеры архитектуры и настройки запуска. Проверьте 16 шагов, guidance=1, 32 visual blocks, 2 text blocks. `attention.type=flash` обозначает dense ветку генератора; фактический движок может быть SDPA.', "from omegaconf import OmegaConf\nconf=OmegaConf.load(SOURCE/'configs/k5_lite_t2v_5s_distil_sd.yaml')\nprint(OmegaConf.to_yaml(conf))"),
('### 3. Параметры и память\n\nBF16 хранит один параметр в 2 байтах, FP32 в 4. Это только веса: нужны ещё активации, временные копии и память ОС. На Mac CPU и GPU используют общий пул; offload не создаёт дополнительную физическую RAM. Qwen загружается целиком, включая неиспользуемые в T2V vision/LM части.', "for label,count in [('Video DiT (округлено)',2e9),('Qwen (округлено)',7e9),('Image DiT (округлено)',6e9)]:\n    print(label, 'BF16 GiB=', round(count*2/2**30,2), 'FP32 GiB=',round(count*4/2**30,2))"),
('### 4. Размер латентного видео\n\nVAE сжимает пространство в 8 раз и время в 4. Для официального 5s пути получается 31 латентный кадр. Декодер даёт 121 кадр: 4×(31−1)+1. При 24 fps это около 5.04 s; название 5s — условное. Patch 1×2×2 даёт 47 616 visual tokens при 512×768.', "seconds,H,W=5,512,768\nT=seconds*24//4+1\nN=T*(H//16)*(W//16)\nprint('latent:',(1,16,T,H//8,W//8),'tokens:',N,'decoded frames:',4*(T-1)+1)\nprint('Наивная BF16 матрица attention для 28 heads, GiB:',round(28*N*N*2/2**30,1))"),
('### 5. Frozen и trainable — проверяем на маленькой сети\n\nЗаморозить означает отключить градиенты весов. `eval()` меняет режим Dropout/BatchNorm, но само по себе не отключает обучение. `no_grad()` отключает запись графа данного вычисления. При обучении генератора внешние энкодеры можно заморозить, а адаптер внутри DiT продолжит учиться.', "external=torch.nn.Linear(4,8).requires_grad_(False).eval()\ntrainable=torch.nn.Linear(8,2)\nx=torch.randn(3,4)\nloss=trainable(external(x)).square().mean(); loss.backward()\nprint('external gradient:',external.weight.grad)\nprint('DiT adapter gradient norm:',trainable.weight.grad.norm().item())"),
('### 6. Где заканчиваются подтверждённые факты\n\nREADME курса содержит training map с источниками. Код инференса явно замораживает Qwen/CLIP; VAE загружается из стороннего checkpoint. Полная историческая настройка optimizer всех этапов не опубликована в этом репозитории. Наш учебный training loop учит маленький DiT; он не воспроизводит промышленное обучение.', "source_excerpt('kandinsky/models/text_embedders.py','self.model = freeze',8)\nsource_excerpt('download_models.py','Qwen/Qwen2.5',9)"),
('### Задания\n\n1. Пересчитайте токены для 10s и 512×512.\n2. Почему 16 шагов сокращают NFE, но почти не уменьшают память хранения DiT?\n3. Составьте список весов, которые нужны только для conditioning, и объясните, когда их можно удалить из памяти.')])

write('01_text_embedders.ipynb','01. text_embedders.py: текст, токены и conditioning','Пройдём от слов до cross-attention. Разберём CLIPTextEmbedder, Qwen2_5_VLTextEmbedder, Kandinsky5TextEmbedder и get_text_embedder. Для настоящих токенизаторов нужен интернет, но не 7B весов.',[
('### 1. Токен — индекс, embedding — вектор\n\nВ учебной таблице одно слово равно одному токену. Настоящие Qwen/CLIP используют подслова: русское слово может занимать несколько индексов. Таблица Embedding делает lookup, а Transformer затем добавляет контекст. Следующий пример демонстрирует только lookup.', "vocab={'<pad>':0,'кот':1,'красная':2,'шапка':3}\nids=torch.tensor([[1,2,3,0]])\nlookup=torch.nn.Embedding(4,6)\nprint(ids.shape, '→',lookup(ids).shape)\nprint('padding mask:',ids!=0)"),
('### 2. Две ветви conditioning\n\nQwen даёт последовательность [B,L,3584] для деталей описания. CLIP даёт pooled [B,768] для общего контекста и смешивания с time embedding. Это `pooler_output`, а не обязательно нормализованное `get_text_features()`. У них разные vocabularies и способы pooling.', "source_excerpt('kandinsky/models/text_embedders.py','class ClipTextEmbedder',29)"),
('### 3. Prompt template и crop\n\nUpstream добавляет системный текст перед пользовательским запросом. Для video отрезаются первые 129 hidden-state позиций, для image — 41. Это фиксированные константы конкретной реализации. Нельзя незаметно сменить tokenizer или шаблон: тогда crop будет означать другой текст.', "from labkit.components import prompt_template\ntemplate,crop=prompt_template('video')\nprint('crop:',crop); print(template.format('Кот медленно поворачивает голову.'))\nsource_excerpt('kandinsky/models/text_embedders.py','max_length = self.max_length + crop_start',24)"),
('### 4. Почему mask и padding важны\n\nPadding выравнивает длины. В bool-маске SDPA True означает разрешённый ключ. Ниже усреднение с mask исключает фиктивные позиции. Это иллюстрация, а не реальный pooling CLIP. Upstream передаёт mask в DiT; внутри Qwen T2V-вызов использует только input_ids — воспроизводим именно его.', "values=torch.tensor([[[1.,2.],[3.,4.],[100.,100.]]])\nmask=torch.tensor([[True,True,False]])\npooled=(values*mask[...,None]).sum(1)/mask.sum(1,keepdim=True)\nprint('без mask:',values.mean(1),'с mask:',pooled)"),
('### 5. Настоящие токенизаторы без больших весов\n\nВключите RUN_TOKENIZERS, чтобы скачать только tokenizer/processor файлы. Сравним русский и английский запросы, количество токенов и truncation. Сначала читаем длины без обрезки; иначе потерю хвоста трудно заметить.', "RUN_TOKENIZERS=False\nif RUN_TOKENIZERS:\n    from huggingface_hub import snapshot_download\n    from transformers import AutoProcessor, CLIPTokenizer\n    from labkit.components import REVISIONS\n    qrepo='Qwen/Qwen2.5-VL-7B-Instruct'; crepo='openai/clip-vit-large-patch14'\n    qp=snapshot_download(qrepo,revision=REVISIONS[qrepo],allow_patterns=['*.json','*.txt','*.jinja','*.model'])\n    cp=snapshot_download(crepo,revision=REVISIONS[crepo],allow_patterns=['*.json','*.txt'])\n    q=AutoProcessor.from_pretrained(qp,use_fast=True).tokenizer\n    c=CLIPTokenizer.from_pretrained(cp)\n    for text in ['Кот в красной шапке','A cat in a red hat','Кот '*400]:\n        for name,tok in [('Qwen',q),('CLIP',c)]:\n            token_ids=tok(text,truncation=False)['input_ids']\n            print(name,len(token_ids),tok.convert_ids_to_tokens(token_ids[:12]))\nelse: print('Настоящие токенизаторы пропущены; веса не скачивались.')"),
('### 6. Настоящие embeddings отдельно от DiT\n\nRUN_ENCODERS загружает Qwen, выполняет один forward, удаляет его, затем загружает CLIP. Большие модели не живут одновременно. Сохранённый conditioning можно повторно использовать для разных seed и sampler, пока текст, шаблон, crop и версии энкодеров совпадают.', "RUN_ENCODERS=False\nif RUN_ENCODERS:\n    from labkit.components import download_component,encode_conditioning\n    for name in ['qwen','clip']: download_component(name)\n    device=device_info()['device']\n    conditioning=encode_conditioning('A cat slowly turns its head.',device=device)\n    for key,value in conditioning.items(): print(key,value.shape,value.dtype)\n    torch.save(conditioning,ROOT/'artifacts/conditioning.pt')\nelse: print('7B энкодер не запускался.')"),
('### 7. Prompt expansion — отдельное действие\n\nМетод expand_text_prompt использует `.generate()` для переписывания запроса. Основной encode использует hidden states одного forward. Это разные задачи и разная latency. Для контролируемого эксперимента отключаем expansion и сохраняем точный запрос.', "source_excerpt('kandinsky/models/text_embedders.py','class Kandinsky5TextEmbedder',30)"),
('### Задания\n\n1. Сравните длины 10 русских и английских описаний.\n2. Выведите, какая часть длинного промпта исчезла при max_length=256/77.\n3. Объясните, почему случайные векторы нужной размерности не заменяют Qwen.\n4. Найдите `.to()` и factory `get_text_embedder`: какие объекты переносятся на устройство?')])

write('02_vae.ipynb','02. vae.py: компактный язык кадров','VAE превращает пиксели в непрерывные латенты. Разберём causal convolution, сжатие времени, posterior, scaling и tiling. KVAE вынесен в отдельную лабораторную: выбранный distill использует HunyuanVideo VAE.',[
('### 1. Почему генерировать в латентах дешевле\n\nВместо RGB [B,3,T,H,W] DiT работает с [T,H/8,W/8,16]. Пространственные размеры меньше, но каналов больше. Формат DiT channels-last, формат VAE channels-first. permute меняет расположение осей, reshape не является заменой permute.', "pixels=torch.zeros(1,3,9,64,64)\nz=torch.zeros(1,16,3,8,8)\nprint('RGB:',pixels.shape,'latent:',z.shape)\nprint('DiT layout:',z[0].permute(1,2,3,0).shape)"),
('### 2. Причинность: будущее не должно менять прошлое\n\nОбычная симметричная convolution смотрит в обе стороны времени. Causal convolution добавляет padding только слева по времени. Ниже меняем последний кадр и убеждаемся, что первые выходы не изменились.', "import torch.nn.functional as F\nconv=torch.nn.Conv3d(1,1,(3,1,1),bias=False)\nx=torch.arange(5.).reshape(1,1,5,1,1)\ndef causal(x): return conv(F.pad(x,(0,0,0,0,2,0),mode='replicate'))\ny=causal(x); changed=x.clone(); changed[:,:,4]=999\nprint(y.flatten()); print(causal(changed).flatten())\nassert torch.allclose(y[:,:,:4],causal(changed)[:,:,:4])"),
('### 3. Вариационность простыми словами\n\nEncoder предсказывает центр μ и разброс σ для каждого латента. mode выбирает центр; sample добавляет шум μ+σ·ε. KL штраф удерживает распределение близко к нормальному. Наша формула диагонального posterior — механизм VAE; это не переобучение Hunyuan.', "mu=torch.tensor([0.2,-0.3]); logvar=torch.tensor([-1.,0.5])\nstd=(0.5*logvar).exp()\nz_sample=mu+std*torch.randn_like(std)\nkl=0.5*(mu.square()+logvar.exp()-1-logvar).sum()\nprint('mode:',mu,'sample:',z_sample,'KL:',kl.item())"),
('### 4. Мини-VAE: encoder, posterior, decoder\n\nСоздадим крошечную сеть для 8×8 картинок. Encoder сжимает 64 числа в 2 координаты, decoder восстанавливает 64. Здесь учатся именно VAE-веса. При обучении Kandinsky эти веса заменяются готовым внешним VAE, а обучается DiT.', "class MiniVAE(torch.nn.Module):\n    def __init__(self):\n        super().__init__(); self.encoder=torch.nn.Sequential(torch.nn.Linear(64,32),torch.nn.SiLU())\n        self.mean=torch.nn.Linear(32,2); self.logvar=torch.nn.Linear(32,2)\n        self.decoder=torch.nn.Sequential(torch.nn.Linear(2,32),torch.nn.SiLU(),torch.nn.Linear(32,64),torch.nn.Sigmoid())\n    def forward(self,x):\n        h=self.encoder(x); mu=self.mean(h); lv=self.logvar(h).clamp(-8,4)\n        z=mu+torch.exp(lv/2)*torch.randn_like(mu)\n        return self.decoder(z),mu,lv\ndata=torch.zeros(32,8,8)\nfor i in range(32): data[i,2:6,i%5:i%5+3]=1\nflat=data.flatten(1); mini=MiniVAE(); opt=torch.optim.Adam(mini.parameters(),lr=0.01)\nlosses=[]\nfor step in range(180):\n    rec,mu,lv=mini(flat)\n    recon_loss=F.mse_loss(rec,flat); kl_loss=0.5*(mu.square()+lv.exp()-1-lv).mean()\n    loss=recon_loss+0.001*kl_loss\n    opt.zero_grad(); loss.backward(); opt.step(); losses.append(loss.item())\nplt.plot(losses); plt.xlabel('training step'); plt.ylabel('reconstruction + KL'); plt.show()"),
('### 5. Как читать результат\n\nНельзя оценивать генеративную модель только по train loss. Сначала проверим реконструкцию mode: два латентных числа явно не сохранят все детали. Затем сравните sample, чтобы увидеть влияние posterior noise.', "with torch.no_grad(): restored=mini.decoder(mini.mean(mini.encoder(flat))).reshape(-1,8,8)\nfig,axes=plt.subplots(1,2); axes[0].imshow(data[2]); axes[0].set_title('input')\naxes[1].imshow(restored[2]); axes[1].set_title('posterior mode'); plt.show()"),
('### 6. Архитектура настоящего vae.py\n\nCausalConv3d → ResnetBlockCausal3D → DownBlock3D → Encoder3D → posterior → Decoder3D → UpBlock3D. MidBlock3D содержит attention на сжатом уровне. UpsampleCausal3D отдельно обрабатывает первый кадр. AutoencoderKLHunyuanVideo объединяет сеть и tiling. build_vae выбирает Hunyuan для video или AutoencoderKL FLUX для image.', "source_excerpt('kandinsky/models/vae.py','def build_vae',17)\nsource_excerpt('kandinsky/models/vae.py','class HunyuanVideoCausalConv3d',40)"),
('### 7. Scaling — часть договора DiT/VAE\n\nПри encoding латент умножают на scaling_factor, перед decoding делят на него. Для Hunyuan в выбранном T2V нет FLUX shift. Неверный scale меняет распределение, которое видит decoder. Проверим обратимость на игрушечном примере.', "raw=torch.randn(1,16,3,8,8); scaling_factor=0.476986\nscaled=raw*scaling_factor\nassert torch.allclose(raw,scaled/scaling_factor,atol=1e-6)\nprint('σ raw:',raw.std().item(),'σ scaled:',scaled.std().item())"),
('### 8. Настоящая реконструкция Hunyuan: только VAE\n\nВключение скачает только vae/*, не DiT и не Qwen. CPU FP32 — проверяемая базовая ветка для Conv3d на Mac. Видео 9×64×64 создано локально. Сначала измеряем качество mode на том же изображении, затем исследуем tiling. PSNR измеряет ошибку пикселей, а не эстетическое качество.', "RUN_REAL_VAE=False\nif RUN_REAL_VAE:\n    from labkit.components import download_component,load_video_vae\n    download_component('vae'); vae=load_video_vae(device='cpu')\n    video=torch.full((1,3,9,64,64),-1.)\n    for t in range(9): video[:,:,t,20:40,5+t*3:21+t*3]=1\n    with torch.inference_mode():\n        posterior=vae.encode(video).latent_dist\n        latent=posterior.mode(); reconstruction=vae.decode(latent).sample.clamp(-1,1)\n    print('latent:',latent.shape,'reconstructed:',reconstruction.shape,'scale:',vae.config.scaling_factor)\n    mse=F.mse_loss((reconstruction+1)/2,(video+1)/2).item()\n    print('PSNR:',-10*np.log10(max(mse,1e-12)))\n    plt.imshow((reconstruction[0,:,4].permute(1,2,0)+1)/2); plt.show()\n    del vae,posterior; release()\nelse: print('Настоящий VAE пропущен.')"),
('### 9. Tiling и ограничения\n\nTiling декодирует перекрывающиеся плитки и смешивает края. Это уменьшает пик памяти, но может изменить результат на границах. В upstream get_enc_optimal_tiling обращается к torch.cuda.mem_get_info: для MPS он непригоден. Наш Mac путь использует diffusers decoder с его tiling и CPU FP32. Это адаптация, не доказанная побитовая эквивалентность.', "source_excerpt('kandinsky/models/vae.py','def blend_v',15)\nsource_excerpt('kandinsky/models/vae.py','def get_enc_optimal_tiling',17)"),
('### Задания\n\n1. Увеличьте KL weight в MiniVAE с 0.001 до 0.1 и сравните reconstruction.\n2. Проверьте sample vs mode на настоящем VAE.\n3. Найдите prepare_causal_attention_mask и объясните значения 0/−inf.\n4. Пересчитайте temporal compression для 1, 9, 121 кадров.')])

write('03_nn_building_blocks.ipynb','03. nn.py: собираем кирпичики DiT','От линейной проекции до RoPE и адаптивной нормализации. Разбираем все классы nn.py на уменьшенных размерах, сохраняя порядок операций.',[
('### 1. Загружаем классы без CUDA compilation\n\nУчебный adapter читает неизменённый файл, убирает декораторы compile/CUDA autocast в отдельном модуле и выбирает FP32. Глобальный torch не меняется. Это позволяет учиться на CPU/MPS; преобразования перечислены в README.', "from labkit.native import load_dit_class\nload_dit_class(torch.float32)\nimport sys\nnn_ref=sys.modules['_k5_lab_float32_128.nn']"),
('### 2. VisualEmbeddings: патч — маленький кубик\n\nБлок 1×2×2 объединяет четыре соседних латентных пикселя. Их каналы склеиваются, затем Linear переводит их в model_dim. В Lite T2V вход содержит 16 noisy + 16 conditioning + 1 mask=33 канала; Linear принимает 132 числа на патч.', "visual=torch.arange(1*4*4*16,dtype=torch.float32).reshape(1,4,4,16)\nlayer=nn_ref.VisualEmbeddings(16,48,(1,2,2))\nembedding=layer(visual)\nprint(visual.shape,'→',embedding.shape,'Linear input:',layer.in_layer.in_features)"),
('### 3. TextEmbeddings и TimeEmbeddings\n\nПроекция текста делает ширину Qwen совместимой с DiT. Время сначала преобразуется в sin/cos разных частот, затем в MLP. CLIP pooled проходит собственную проекцию и складывается с time embedding. Это conditioning нормализаций, а не дополнительный visual token.', "text_proj=nn_ref.TextEmbeddings(32,48); clip_proj=nn_ref.TextEmbeddings(16,32)\ntime_proj=nn_ref.TimeEmbeddings(48,32)\ntext=torch.randn(1,6,32); pooled=torch.randn(1,16)\ntime=time_proj(torch.tensor([500.]))+clip_proj(pooled)\nprint('text:',text_proj(text).shape,'time+CLIP:',time.shape)"),
('### 4. RoPE1D: поворот вместо прибавления позиции\n\nRoPE вращает пары координат Query/Key. Одновременный поворот сохраняет скалярное произведение, разные повороты кодируют относительное положение. В коде последняя ось разбивается на пары. Пример с 2D объясняет механику без большой матрицы.', "angle=torch.tensor(0.6)\nR=torch.stack([torch.stack([angle.cos(),-angle.sin()]),torch.stack([angle.sin(),angle.cos()])])\na=torch.tensor([1.,2.]); b=torch.tensor([3.,-1.])\nprint('dot before:',a@b,'after:',(R@a)@(R@b))\nrope=nn_ref.RoPE1D(12)(torch.arange(6))\nprint('RoPE1D:',rope.shape)"),
('### 5. RoPE3D: три координаты\n\nЧасти head_dim отвечают времени, высоте и ширине. Для Lite axes_dims=(16,24,24), head_dim=64, model_dim/head_dim=28 heads. scale_factor=(1,2,2) масштабирует позиционные частоты, а не размеры тензора.', "rope3=nn_ref.RoPE3D((4,4,4))\npos=[torch.arange(1),torch.arange(2),torch.arange(2)]\nprint('3D rotations:',rope3((1,2,2),pos,(1,2,2)).shape)"),
('### 6. Modulation: время меняет обработку признаков\n\nMLP выдаёт shift, scale и gate. После norm вычисляется norm(x)·(1+scale)+shift; residual добавляет gate·out. Нулевая инициализация modulation даёт gate=0 и сохраняет исходный residual на старте обучения.', "mod=nn_ref.Modulation(32,48,3)\nshift,scale,gate=mod(time).chunk(3,-1)\nx=torch.randn(1,4,48); norm=torch.nn.LayerNorm(48,elementwise_affine=False)\nz=nn_ref.apply_scale_shift_norm(norm,x,scale,shift)\nresult=nn_ref.apply_gate_sum(x,z,gate)\nprint('gate max:',gate.abs().max().item(),'residual change:',(result-x).abs().max().item())"),
('### 7. Три attention-класса\n\nMultiheadSelfAttentionEnc обрабатывает text tokens и padding. MultiheadSelfAttentionDec обрабатывает visual tokens и может выбирать NABLA. MultiheadCrossAttention берёт Q из visual, K/V из text. Все используют Q/K RMSNorm. Код ниже проверяет формы; веса случайные, выход не несёт семантики.', "enc=nn_ref.MultiheadSelfAttentionEnc(48,12,'sdpa',True)\ndec=nn_ref.MultiheadSelfAttentionDec(48,12,'sdpa')\ncross=nn_ref.MultiheadCrossAttention(48,12,'sdpa',True)\ntext48=text_proj(text); vis48=embedding.reshape(1,4,48)\nprint('text self:',enc(text48,rope,torch.ones(1,6,dtype=torch.bool)).shape)\nvisual_rope=rope3((1,2,2),pos).reshape(4,1,6,2,2)\nprint('visual self:',dec(vis48,visual_rope).shape)\nprint('cross:',cross(vis48,text48).shape)"),
('### 8. FeedForward и OutLayer\n\nFeedForward расширяет размерность, применяет GELU и сжимает обратно. OutLayer использует modulation, norm и Linear, затем разворачивает патчи в исходную решётку. Предсказываются 16 каналов velocity, а не RGB.', "ff=nn_ref.FeedForward(48,96); out=nn_ref.OutLayer(48,32,16,(1,2,2))\nprint('FF:',ff(vis48).shape)\nprint('unpatchified velocity:',out(embedding,text48,time).shape)"),
('### Задания\n\n1. Вручную воспроизведите VisualEmbeddings с reshape → permute → flatten → Linear.\n2. Почему model_dim должен делиться на sum(axes_dims)?\n3. Измените gate на 1 и проверьте residual.\n4. Проследите dtype в apply_rotary: расчёт FP32, затем приведение к рабочему dtype.')])

write('04_attention.ipynb','04. attention.py: как токены смотрят друг на друга','Сначала реализуем attention из трёх операций, затем сравним с SDPA. Объясним движки FlashAttention/Sage/SDPA и причину большого расхода памяти в видео.',[
('### 1. Query, Key, Value — вопрос, адрес, содержимое\n\nQuery каждого токена сравнивается с Key других. Softmax превращает оценки в веса; Value смешиваются с этими весами. Деление на sqrt(head_dim) удерживает величины оценок разумными.', "import torch.nn.functional as F\nq=torch.randn(1,2,5,4); k=torch.randn(1,2,5,4); v=torch.randn(1,2,5,4)\nscores=q@k.transpose(-1,-2)/np.sqrt(q.shape[-1])\nweights=scores.softmax(-1); manual=weights@v\nprint('scores:',scores.shape,'sum rows:',weights.sum(-1))\nplt.imshow(weights[0,0]); plt.xlabel('key'); plt.ylabel('query'); plt.show()"),
('### 2. Воспроизводим SDPA\n\nPyTorch SDPA вычисляет ту же операцию, но может выбирать эффективный backend. В upstream вход [B,L,H,D] транспонируют в [B,H,L,D]. Проверка ниже ловит ошибки осей и масштаба.', "sdpa=F.scaled_dot_product_attention(q,k,v)\nprint('max error:',(manual-sdpa).abs().max().item())\nassert torch.allclose(manual,sdpa,atol=1e-5)\nsource_excerpt('kandinsky/models/attention.py','def sdpa',21)"),
('### 3. Mask: запрещённые связи\n\nTrue в bool SDPA mask разрешает связь. В float-маске 0 разрешает, −inf запрещает. Мы запрещаем последний ключ и сравниваем API с явным softmax. Нельзя подставлять bool-маску с противоположным смыслом из другого API.', "mask=torch.tensor([True,True,True,True,False])[None,None,None,:]\nmasked_manual=scores.masked_fill(~mask,float('-inf')).softmax(-1)@v\nmasked_sdpa=F.scaled_dot_product_attention(q,k,v,attn_mask=mask)\nassert torch.allclose(masked_manual,masked_sdpa,atol=1e-5)\nprint('Изменение после mask:',(masked_sdpa-manual).abs().mean().item())"),
('### 4. Query chunking без потери ключей\n\nПри dense attention каждый запрос независим от других запросов. Поэтому можно обрабатывать Query порциями, сохраняя полный K/V. Это снижает размер временной матрицы, но не число сравнений. Разделить K/V и независимо применить softmax было бы неверно.', "chunked=torch.cat([F.scaled_dot_product_attention(q[:,:,i:i+2],k,v) for i in range(0,5,2)],dim=2)\nassert torch.allclose(chunked,sdpa,atol=1e-5)\nprint('chunked max error:',(chunked-sdpa).abs().max().item())"),
('### 5. Масштаб видео\n\nУвеличение H и W вдвое даёт в 4 раза больше токенов и до 16 раз больше элементов dense attention. FlashAttention избегает хранения полной матрицы, но dense вычисления остаются квадратичными. Наш Mac adapter использует query chunks; он может быть медленнее оптимизированного CUDA.', "for seconds,H,W in [(1,256,256),(5,512,512),(5,512,768),(10,512,768)]:\n    n=(seconds*6+1)*(H//16)*(W//16)\n    print((seconds,H,W),'tokens',n,'dense/head FP32 GiB',round(n*n*4/2**30,2))"),
('### 6. SelfAttentionEngine: выбор реализации\n\nflash_attention_2/3 и sage требуют соответствующих библиотек. auto проверяет их наличие и иначе выбирает sdpa. MPS-путь курса выбирает только SDPA без compile. В CUDA Colab начните с SDPA, а затем измеряйте альтернативы по одинаковым prompt/seed.', "source_excerpt('kandinsky/models/attention.py','class SelfAttentionEngine',56)"),
('### Задания\n\n1. Измените Key одного токена и покажите изменение весов.\n2. Сделайте causal mask через tril и сравните с padding mask.\n3. Замерьте 3 повторения SDPA после прогрева и синхронизации устройства.\n4. Докажите экспериментом, что chunking по Key с отдельными softmax неверен.')])

write('05_utils_and_nabla.ipynb','05. utils.py: позиции, перестановки и NABLA','Этот файл содержит функции, а не новую обучаемую модель. Разберём exist, freeze, get_freqs, local_patching/local_merge, fractal_flatten/unflatten, fast_sta_nabla и nablaT_v2.',[
('### 1. Что здесь имеет веса\n\nexist проверяет None, freeze отключает requires_grad, get_freqs строит фиксированные частоты. Они не имеют optimizer state. NABLA строит mask из текущих Q/K: обучаемые проекции остаются в DiT, алгоритм выбора блоков сам не является отдельной сетью.', "from labkit.native import load_dit_class\nload_dit_class(torch.float32)\nimport sys\nu=sys.modules['_k5_lab_float32_128.utils']\nprint('exist(None):',u.exist(None),'frequencies:',u.get_freqs(6))\nlayer=u.freeze(torch.nn.Linear(3,4)); print('trainable:',sum(p.numel() for p in layer.parameters() if p.requires_grad))"),
('### 2. local_patching — сложить соседей рядом\n\nЛатентная решётка хранит пространственные позиции, а attention работает с последовательностью. Для sparse блоков полезно поставить соседей подряд. Пронумеруем клетки, чтобы видеть permutation без случайных значений.', "x=torch.arange(1*4*4).reshape(1,4,4,1)\npatches=u.local_patching(x,(1,4,4),(1,2,2))\nrestored=u.local_merge(patches,(1,4,4),(1,2,2))\nprint('original:\\n',x[0,:,:,0]); print('groups:\\n',patches[:,:,0])\nassert torch.equal(x,restored)"),
('### 3. fractal_flatten: dense и block ветви\n\nНазвание не означает изменение значений. Dense flatten просто склеивает T/H/W. В sparse ветви группы 1×8×8 переставляются вместе с RoPE, чтобы позиции остались соответствующими токенам. Проверяем обратную операцию на 16×16.', "x=torch.arange(1*16*16,dtype=torch.float32).reshape(1,16,16,1)\nrope=x.clone()\nflat,flat_rope=u.fractal_flatten(x,rope,(1,16,16),block_mask=True)\nback=u.fractal_unflatten(flat,(1,16,16),block_mask=True)\nassert torch.equal(x,back)\nprint('first 16 reordered indices:',flat[:16,0])"),
('### 4. Простой block selector\n\nУчебная версия NABLA: сжимаем Query/Key по 4 токена, считаем attention между блоками, сохраняем самые вероятные блоки до накопленной массы P. Пересекающий порог блок включаем. Это иллюстрация отбора, не полная implementation fast_sta_nabla/nablaT_v2.', "q=torch.randn(16,8); k=torch.randn(16,8)\nqb=q.reshape(4,4,8).mean(1); kb=k.reshape(4,4,8).mean(1)\nprob=(qb@kb.T/np.sqrt(8)).softmax(-1)\nvalues,order=prob.sort(-1,descending=True)\nP=0.7\nkeep_sorted=(values.cumsum(-1)-values)<P\nkeep=torch.zeros_like(keep_sorted).scatter(-1,order,keep_sorted)\nprint('kept fraction:',keep.float().mean().item())\nfig,axes=plt.subplots(1,2); axes[0].imshow(prob); axes[1].imshow(keep); plt.show()"),
('### 5. STA добавляет локальных соседей\n\nЧисто вероятностный отбор может терять близкие пространственные связи. Локальная маска объединяется с adaptive mask. Упрощённая 1D версия ниже гарантирует диагональ и соседей. Настоящий STA использует временно-пространственную геометрию.', "indices=torch.arange(4)\nlocal=(indices[:,None]-indices[None,:]).abs()<=1\ncombined=keep|local\nprint('adaptive:\\n',keep.int(),'combined:\\n',combined.int())"),
('### 6. Где применяется настоящий NABLA\n\n10s checkpoints используют NABLA; выбранный distill 5s использует dense attention. FlexAttention/NABLA в MPS-порт курса не включены. Не называйте замену sparse на dense эквивалентным восстановлением 10s модели без проверки.', "source_excerpt('kandinsky/models/utils.py','def fast_sta_nabla',28)\nsource_excerpt('kandinsky/models/utils.py','def nablaT_v2',55)"),
('### Задания\n\n1. Проверьте inverse permutation на случайных T/H/W, кратных размерам блоков.\n2. Исследуйте P=0.3/0.7/0.95 и долю сохранённых блоков.\n3. Объясните, почему перестановку необходимо применить и к RoPE.\n4. Найдите место передачи sparse_params из generation_utils в DiT.')])

write('06_dit_and_flow_matching.ipynb','06. dit.py + Flow Matching: что именно учится','DiT — сеть скорости движения в латентном пространстве. Сделаем настоящий forward уменьшенной официальной архитектуры и отдельное учебное обучение velocity. Не обучаем 2B модель на ноутбуке.',[
('### 1. Классы dit.py\n\nTransformerEncoderBlock уточняет текст через self-attention и FFN. TransformerDecoderBlock обрабатывает visual tokens через self-attention → cross-attention → FFN. DiffusionTransformer3D связывает embeddings, RoPE, блоки и OutLayer. get_dit — factory. В README дан перечень внутренних trainable весов.', "source_excerpt('kandinsky/models/dit.py','class TransformerDecoderBlock',43)"),
('### 2. Настоящая архитектура, маленькие размеры\n\nУменьшаем ширину и количество блоков, но сохраняем те же классы. На вход 33 канала: 16 шумовых, 16 нулевых visual conditioning, 1 нулевая маска T2V. На выход 16 каналов velocity. Такой forward позволяет проверить contract без больших весов.', "from labkit.native import tiny_dit\nmodel=tiny_dit(LAB_DEVICE)\nx=torch.randn(1,4,4,16,device=LAB_DEVICE)\ninput33=torch.cat([x,torch.zeros_like(x),torch.zeros_like(x[...,:1])],-1)\ntext=torch.randn(1,6,32,device=LAB_DEVICE); pooled=torch.randn(1,16,device=LAB_DEVICE)\npos=[torch.arange(1,device=LAB_DEVICE),torch.arange(2,device=LAB_DEVICE),torch.arange(2,device=LAB_DEVICE)]\nwith torch.no_grad(): velocity=model(input33,text,pooled,torch.tensor([500.],device=LAB_DEVICE),pos,torch.arange(6,device=LAB_DEVICE))\nprint('parameters:',sum(p.numel() for p in model.parameters()),'input:',input33.shape,'output:',velocity.shape)"),
('### 3. Увидим промежуточные формы\n\nForward hooks наблюдают выход, не меняя модель. Сначала visual projection выдаёт решётку [T,H/2,W/2,D]; перед блоками она превращается в [1,N,D]. OutLayer возвращает [T,H,W,16].', "shapes={}\ndef hook(name):\n    def record(module,args,out):\n        if isinstance(out,torch.Tensor): shapes[name]=tuple(out.shape)\n    return record\nhandles=[module.register_forward_hook(hook(name)) for name,module in model.named_modules() if name in ['visual_embeddings','text_embeddings','visual_transformer_blocks.0','out_layer']]\nwith torch.no_grad(): model(input33,text,pooled,torch.tensor([500.],device=LAB_DEVICE),pos,torch.arange(6,device=LAB_DEVICE))\nfor h in handles: h.remove()\nprint(shapes)"),
('### 4. Flow Matching: учим направление, а не картинку\n\nВыбираем convention, совпадающий с decreasing-time sampler: x₀ — data, ε — noise, xₜ=(1−t)x₀+tε. Производная по t равна ε−x₀. Учим сеть предсказывать эту velocity. При sampling идём t:1→0, поэтому Δt отрицательно. Маленький пример доказывает знак.', "data=torch.tensor([2.,-1.]); noise=torch.tensor([-0.5,0.4]); t=0.7\nxt=(1-t)*data+t*noise; target=noise-data\nprint('mixed:',xt,'velocity:',target)\nprint('one exact step noise→data:',noise-target)\nassert torch.allclose(noise-target,data)"),
('### 5. Учебное обучение того же tiny DiT\n\nВозьмём единственный фиксированный data latent. Каждый шаг рисует новые noise и t. Это намеренно простая задача: уменьшение loss показывает, что градиенты доходят до DiT, но не доказывает освоение изображений или текста. Frozen conditioning ниже — сохранённые случайные векторы, а не Qwen.', "model.train(); optimizer=torch.optim.Adam(model.parameters(),lr=0.002)\ndata_latent=torch.ones_like(x)*0.3\nlosses=[]\nfor step in range(100):\n    t=torch.rand(1,device=LAB_DEVICE); noise=torch.randn_like(x)\n    xt=(1-t)*data_latent+t*noise\n    input33=torch.cat([xt,torch.zeros_like(xt),torch.zeros_like(xt[...,:1])],-1)\n    prediction=model(input33,text.detach(),pooled.detach(),t*1000,pos,torch.arange(6,device=LAB_DEVICE))\n    target=noise-data_latent\n    loss=torch.nn.functional.mse_loss(prediction,target)\n    optimizer.zero_grad(); loss.backward(); optimizer.step(); losses.append(loss.item())\nplt.plot(losses); plt.ylabel('velocity MSE'); plt.xlabel('step'); plt.show()\nprint('first 10 mean:',np.mean(losses[:10]),'last 10 mean:',np.mean(losses[-10:]))"),
('### 6. Проверяем loss на новых noise/t\n\nИспользуем 20 новых пар, не делая optimizer.step. Обобщение здесь ограничено одним data latent. Следующий уровень — набор латентов и осмысленный conditioning; промышленное обучение требует данных и compute, которых этот курс не воспроизводит.', "model.eval(); validation=[]\nwith torch.no_grad():\n    for _ in range(20):\n        t=torch.rand(1,device=LAB_DEVICE); eps=torch.randn_like(x); xt=(1-t)*data_latent+t*eps\n        inp=torch.cat([xt,torch.zeros_like(xt),torch.zeros_like(xt[...,:1])],-1)\n        pred=model(inp,text,pooled,t*1000,pos,torch.arange(6,device=LAB_DEVICE))\n        validation.append(torch.nn.functional.mse_loss(pred,eps-data_latent).item())\nprint('validation MSE:',np.mean(validation))"),
('### 7. Структура обучаемых весов\n\nQwen hidden states frozen, но text_embeddings и Linguistic Token Refiner внутри DiT обучаются. Равным образом CLIP frozen, но pooled_text_embeddings обучается. RoPE частоты — buffers, не параметры. Эта граница особенно важна при LoRA.', "groups={}\nfor name,p in model.named_parameters():\n    group=name.split('.')[0]; groups[group]=groups.get(group,0)+p.numel()\nprint(groups)\nprint('buffers:',[(n,tuple(b.shape)) for n,b in model.named_buffers()])"),
('### Задания\n\n1. Поменяйте знак target и объясните, почему reverse sampler пойдёт неверно.\n2. Сделайте два data latent с разным conditioning и исследуйте, использует ли модель текст.\n3. Заморозьте все параметры кроме out_layer: как изменится скорость обучения?\n4. Сравните random tiny DiT и trained tiny DiT; не делайте выводов о качестве pretrained 2B модели.')])

write('07_sampling.ipynb','07. Sampling: превращаем velocity в траекторию','Разберём Euler, shifted schedule, classifier-free guidance, distillation и NFE. Сначала точная простая система, затем связь с generate/get_velocity.',[
('### 1. Одна строка sampler\n\nEuler говорит: новое положение = текущее + длительность шага × скорость. В Kandinsky timestep уменьшается, поэтому шаг отрицательный. Покажем постоянную velocity, где Euler точен даже с одним шагом.', "noise=torch.tensor([1.5,-0.3]); data=torch.tensor([0.2,0.7]); v=noise-data\nx=noise.clone(); schedule=shifted_schedule(16,5)\ntrajectory=[x.clone()]\nfor dt in schedule.diff(): x=x+dt*v; trajectory.append(x.clone())\nprint('end:',x,'expected:',data)\nassert torch.allclose(x,data,atol=1e-6)"),
('### 2. Shifted schedule\n\nt′=s·t/(1+(s−1)t). s меняет плотность временных точек; начальная и конечная точки остаются 1 и 0. YAML distill содержит scheduler_scale=5, но pipeline.__call__ по умолчанию использует 10. В курсе передаём 5 явно и сохраняем его в отчёт; можно сравнить 5/10 как эксперимент.', "for scale in [1,3,5,10]:\n    times=shifted_schedule(16,scale)\n    plt.plot(range(17),times,marker='.',label=f's={scale}')\nplt.xlabel('step'); plt.ylabel('time'); plt.legend(); plt.show()\nassert torch.all(schedule.diff()<0)\nprint('sum Δt:',schedule.diff().sum().item())"),
('### 3. Нелинейная velocity и ошибка Euler\n\nНа постоянном поле больше шагов ничего не улучшает. Для нелинейного по времени поля ошибка уже зависит от шага. Здесь dx/dt=x, x(1)=1, точный ответ x(0)=e⁻¹. Это учебная ODE, не Kandinsky velocity.', "errors=[]\nfor steps in [4,8,16,32,64]:\n    x=torch.tensor(1.); times=shifted_schedule(steps,1)\n    for dt in times.diff(): x=x+dt*x\n    error=abs(x.item()-np.exp(-1)); errors.append(error)\n    print(steps,x.item(),error)\nplt.loglog([4,8,16,32,64],errors,'o-'); plt.xlabel('Euler steps'); plt.ylabel('absolute error'); plt.show()"),
('### 4. CFG требует двух вызовов\n\nv=v_uncond+w·(v_cond−v_uncond). При w=1 это v_cond: upstream пропускает uncond forward. Distill checkpoint научился использовать одну ветвь. Guidance=1 здесь не означает отсутствие text conditioning.', "cond=torch.tensor([2.,1.]); uncond=torch.tensor([0.,-1.])\nfor w in [0.,1.,3.,5.]: print(w,uncond+w*(cond-uncond))\nfor label,steps,w in [('SFT',50,5),('noCFG',50,1),('distill',16,1)]:\n    print(label,'steps',steps,'NFE',steps*(1 if w==1 else 2))"),
('### 5. Distillation не уменьшает архитектуру\n\nSFT, noCFG и distilled16steps имеют одинаковые основные размеры DiT. Различаются обученные веса и рекомендуемый режим. Поставить num_steps=16 на SFT — не то же самое, что загрузить distill. Heun требует дополнительный forward; он здесь учебный, не официальная рекомендация для 16-step checkpoint.', "from omegaconf import OmegaConf\nfor suffix in ['sft','nocfg','distil']:\n    cfg=OmegaConf.load(SOURCE/f'configs/k5_lite_t2v_5s_{suffix}_sd.yaml')\n    print(suffix,'steps',cfg.model.num_steps,'guidance',cfg.model.guidance_weight,'width',cfg.model.dit_params.model_dim)"),
('### 6. Связываем с кодом\n\nget_velocity передаёт t×1000 в DiT и при необходимости делает CFG. generate создаёт timesteps, visual conditioning и Euler update. Для T2V first_frames=None. Для I2V первый латент фиксируется: это дополнительное условие, не смена text tokenizer.', "source_excerpt('kandinsky/generation_utils.py','def get_velocity',49)\nsource_excerpt('kandinsky/generation_utils.py','timesteps = torch.linspace',47)"),
('### 7. Протокол честного сравнения\n\nМеняем один фактор: seed, steps, scale или checkpoint. Для latency отделяем загрузку, text encoding, sampling, decoding и запись файла. GPU вычисляет асинхронно: синхронизация перед/после замера обязательна. Не сравниваем холодный первый запуск с прогретым.', "from labkit.common import save_json\nexperiment={'checkpoint':'distilled16steps-5s','seed':42,'steps':16,'NFE':16,'guidance':1.,'scheduler_scale':5.,'height':512,'width':768,'source_revision':REVISION,'measured':False}\nsave_json(ROOT/'artifacts/sampling_protocol.json',experiment)\nprint(experiment)"),
('### Задания\n\n1. Сравните Euler и Heun на dx/dt=x, считая NFE.\n2. Почему NFE=100 в таблице SFT соответствует 50 шагам с CFG?\n3. Для distill сравните 8/16/24 steps и не предполагайте монотонное качество.\n4. Объясните разницу noise seed на CPU и CUDA: одинаковое число не гарантирует одинаковый tensor.')])

write('08_parallelize.ipynb','08. parallelize.py: распределяем математику','На одном GPU Mac/Colab процессы не нужны. Разберём parallelize_dit, get_module_by_name, update_plan_for_lora и parallelize_seq через проверяемые CPU-эквиваленты матричных операций.',[
('### 1. Data, tensor и sequence parallel\n\nData parallel делит примеры, tensor parallel делит веса/каналы внутри слоя, sequence parallel делит токены. FSDP хранит шарды весов и собирает нужные параметры. Это разные способы уменьшить память и распределить работу; ни один не меняет число обученных параметров.', "source_excerpt('kandinsky/models/parallelize.py','def parallelize_dit',31)"),
('### 2. ColwiseParallel — делим выходные признаки\n\nДля Linear y=xWᵀ+b разделим строки W (выходные каналы). Каждый виртуальный участник вычисляет свою часть y, затем concatenate собирает результат. Название colwise относится к логической матричной операции; PyTorch хранит W в [out,in].', "x=torch.randn(5,6); W=torch.randn(8,6); b=torch.randn(8)\nfull=x@W.T+b\nparts=[x@w.T+bb for w,bb in zip(W.chunk(2,0),b.chunk(2,0))]\nassembled=torch.cat(parts,-1)\nassert torch.allclose(full,assembled,atol=1e-6)\nprint('shard outputs:',[p.shape for p in parts])"),
('### 3. RowwiseParallel — складываем частичные суммы\n\nРазделяем входные признаки и соответствующие столбцы W. Частичные результаты суммируются all_reduce. Bias прибавляется один раз после sum; добавление bias каждым участником даст ошибку.', "partial=[xx@ww.T for xx,ww in zip(x.chunk(2,-1),W.chunk(2,-1))]\nassembled=sum(partial)+b\nassert torch.allclose(full,assembled,atol=1e-6)\nprint('max difference:',(assembled-full).abs().max().item())"),
('### 4. Sequence parallel и глобальный контекст\n\nFFN/LayerNorm работают независимо по токенам: можно делить sequence и собрать обратно. Self-attention требует доступа к остальным K/V; локальный attention на каждом шарде без обмена ошибочен. Покажем различие на малой задаче.', "import torch.nn.functional as F\nq=torch.randn(1,1,8,4); k=torch.randn_like(q); v=torch.randn_like(q)\ncorrect=F.scaled_dot_product_attention(q,k,v)\nlocal=torch.cat([F.scaled_dot_product_attention(qq,kk,vv) for qq,kk,vv in zip(q.chunk(2,2),k.chunk(2,2),v.chunk(2,2))],2)\nprint('ошибка без global KV:',(correct-local).abs().mean().item())"),
('### 5. LoRA меняет имена вложенных модулей\n\nget_module_by_name проходит dotted path, включая ModuleList indices. update_plan_for_lora переносит parallelization plan на base_layer и adapter layers. Только LoRA A/B можно сделать trainable, базовый DiT оставить frozen. Это способ адаптации, а не часть обязательного T2V инференса.', "tree=torch.nn.Module(); tree.blocks=torch.nn.ModuleList([torch.nn.Linear(3,4)])\ndef get_module_by_name(root,path):\n    for name in path.split('.'): root=getattr(root,name)\n    return root\nprint(get_module_by_name(tree,'blocks.0'))\nsource_excerpt('kandinsky/models/parallelize.py','def update_plan_for_lora',23)"),
('### 6. parallelize_seq в настоящем коде\n\nДля нескольких GPU используется DeviceMesh и DTensor layouts Shard/Replicate. Не вызываем distributed launch внутри notebook с одной GPU. Даже Colab A100 — это один device; параллелизм нескольких GPU проверяется отдельно на соответствующем сервере.', "source_excerpt('kandinsky/models/parallelize.py','def parallelize_seq',65)"),
('### Задания\n\n1. Повторите Linear decomposition для 4 shards.\n2. Сделайте намеренную ошибку с bias и измерьте разницу.\n3. Найдите PrepareModuleInput/Output: какие layouts меняются?\n4. Объясните, почему M3 Max 40 GPU cores не равны 40 CUDA devices.\n5. Для multi-GPU исследования используйте официальный test.py; наши проверки воспроизводят математику, а не сетевые collectives.')])

write('09_local_m3_max.ipynb','09. M3 Max: последовательный distill 5s','Экспериментальный локальный маршрут: Qwen → сохранённый conditioning → DiT MPS → сохранённые latents → Hunyuan CPU decoder → MP4. Реальный запуск включается вручную; полная генерация может быть долгой.',[
('### 1. Сначала проверка MPS\n\nНа M3 Max 48 ГБ память общая. Не отключаем системные memory limits. BF16 нужен для разумной памяти Qwen/DiT; проверим matmul, SDPA и autocast. Conv3d декодер оставляем на CPU FP32. Успех маленького smoke test не доказывает, что весь 5s запуск поместится.', "MPS_AVAILABLE=torch.backends.mps.is_available()\nprint('MPS available:',MPS_AVAILABLE)\nif MPS_AVAILABLE:\n    import torch.nn.functional as F\n    a=torch.randn(1,2,8,16,device='mps',dtype=torch.bfloat16)\n    with torch.autocast('mps',dtype=torch.bfloat16): out=F.scaled_dot_product_attention(a,a,a)\n    torch.mps.synchronize(); print(out.shape,out.dtype,torch.isfinite(out).all().item())\n    del a,out; release()"),
('### 2. Forward настоящих классов на Metal\n\nЭта проверка использует tiny DiT: она ловит неподдерживаемые операции, а не проверяет pretrained weights. Если ошибка возникает здесь, сначала разберите traceback; переход к большим весам её не исправит.', "if MPS_AVAILABLE:\n    from labkit.native import tiny_dit\n    m=tiny_dit('mps')\n    with torch.inference_mode():\n        y=m(torch.randn(1,4,4,33,device='mps'),torch.randn(1,6,32,device='mps'),torch.randn(1,16,device='mps'),torch.tensor([500.],device='mps'),[torch.arange(1,device='mps'),torch.arange(2,device='mps'),torch.arange(2,device='mps')],torch.arange(6,device='mps'))\n    print('tiny MPS velocity:',y.shape,'finite:',torch.isfinite(y).all().item())\n    del m,y; release()"),
('### 3. Скачивание только выбранных компонентов\n\nЭто десятки ГБ на диске. Перечень и pinned revisions сохранены в reference/hf-revisions.json. Токен Hugging Face берётся из стандартного окружения HF_TOKEN/login, в notebook его не печатаем. Qwen/CLIP/VAE скачиваются отдельно от DiT.', "DOWNLOAD_WEIGHTS=False\nif DOWNLOAD_WEIGHTS:\n    from labkit.components import download_component\n    for name in ['qwen','clip','dit','vae']: print(name,download_component(name))\nelse: print('Веса не скачивались. Для загрузки задайте DOWNLOAD_WEIGHTS=True.')"),
('### 4. Проверим файлы до запуска\n\nstrict state_dict loading защищает от случайного смешивания SFT/distill архитектуры. Путь должен содержать именно distilled16steps_5s. Загрузка внутри model с meta parameter placeholders уменьшает лишнюю временную копию весов.', "required=[ROOT/'weights/dit/model/kandinsky5lite_t2v_distilled16steps_5s.safetensors',ROOT/'weights/qwen/config.json',ROOT/'weights/clip/config.json',ROOT/'weights/vae/vae/config.json']\nfor p in required: print(p.relative_to(ROOT),p.exists())"),
('### 5. Первый небольшой запуск\n\n1s 256×256, 16 steps — проверка формы/ресурсов, вне официального списка resolutions. Качество такого вывода не характеризует distill checkpoint. Малый запуск не заменяет финальный 5s 512×768. Expansion выключен; guidance=1; scale=5 задан явно.', "RUN_SMALL=False\nif RUN_SMALL:\n    assert MPS_AVAILABLE,'Нужен MPS'\n    assert all(p.exists() for p in required),'Сначала скачайте компоненты'\n    from labkit.components import sequential_t2v\n    path=sequential_t2v('A red toy car slowly moves across a wooden table.',height=256,width=256,seconds=1,device='mps',output=ROOT/'artifacts/mac_small.mp4')\n    from IPython.display import Video,display\n    display(Video(str(path),embed=True))\nelse: print('Малый pretrained запуск пропущен.')"),
('### 6. Финальный 5s маршрут\n\nЗапускаем только после малого теста. Каждый компонент удаляется перед следующим; сохранённые conditioning и latents позволяют не повторять предыдущую стадию при сбое декодирования. JSON рядом с MP4 содержит версии, seed, NFE и stage timings. CPU VAE decoding может стать самым медленным этапом.', "RUN_FULL_5S=False\nif RUN_FULL_5S:\n    assert MPS_AVAILABLE and all(p.exists() for p in required)\n    from labkit.components import sequential_t2v\n    path=sequential_t2v('A cat in a red hat slowly turns its head. Static camera, warm daylight.',output=ROOT/'artifacts/mac_distill_5s.mp4')\n    from IPython.display import Video,display\n    display(Video(str(path),embed=True))\nelse: print('Полный 5s инференс НЕ выполнялся.')"),
('### 7. Возобновление только decoder\n\nЕсли latents уже сохранены, повторный DiT не нужен. torch.load(weights_only=True) ограничивает содержимое загружаемого файла. Загружайте собственные tensor artifacts. При изменении VAE версии старые latents требуют проверки совместимости.', "RUN_RESUME_DECODE=False\nif RUN_RESUME_DECODE:\n    from labkit.components import decode_latents\n    latent=torch.load(ROOT/'artifacts/mac_distill_5s.latents.pt',map_location='cpu',weights_only=True)\n    frames=decode_latents(latent)\n    import imageio.v2 as imageio\n    imageio.mimwrite(ROOT/'artifacts/mac_resumed.mp4',frames,fps=24,codec='libx264')\nelse: print('Resume decode пропущен.')"),
('### Ограничения и задания\n\n1. Измерьте RSS и torch.mps.current_allocated_memory между стадиями; не складывайте их как независимые физические пулы.\n2. Начните с restart kernel после OOM, а затем уменьшите resolution/seconds.\n3. Сравните query_chunk=64/128/256 и peak memory.\n4. CUDA NF4/BitsAndBytes не используется на Mac.\n5. Отличия порта: eager, query chunking, CPU RNG, masked padded text, diffusers CPU VAE; побитовая идентичность официальному CUDA не заявляется.')])

write('10_colab_cuda_distill.ipynb','10. Colab CUDA: официальный distill 5s','Путь к полноценной генерации на NVIDIA. Включайте тяжёлые ячейки отдельно; все учебные лабы 00–08 также можно выполнять в Colab без GPU.',[
('### 1. Выбираем runtime\n\nRuntime → Change runtime type → GPU. Colab не гарантирует модель GPU и время доступа. T4 поддерживает FP16, но не аппаратный BF16; официальный код широко использует BF16. Для этого маршрута нужен BF16-capable GPU, предпочтительно A100/L4. Мало VRAM: сначала conditioning на CPU, offload, VAE tiling; успешный запуск не гарантируется.', "print('CUDA:',torch.cuda.is_available())\nif torch.cuda.is_available():\n    print(torch.cuda.get_device_name(0),'VRAM GiB:',torch.cuda.get_device_properties(0).total_memory/2**30)\n    print('BF16:',torch.cuda.is_bf16_supported())\nelse: print('Здесь проверяется только подготовка; нужен GPU runtime для инференса.')"),
('### 2. Подготовка официальной среды\n\nИспользуем уже сохранённую pinned копию кода reference/kandinsky-5. В notebook путь до кода добавляется явно. Дополнительные зависимости нужны официальному pipeline: torchvision, peft, av, opencv. Ячейка установки отключена по умолчанию. При замене PyTorch перезапустите runtime перед импортами.', "INSTALL_CUDA_EXTRAS=False\nif INSTALL_CUDA_EXTRAS:\n    import subprocess\n    subprocess.check_call([sys.executable,'-m','pip','install','torchvision==0.23.0','peft>=0.17,<0.18','av','opencv-python-headless'])\nelse: print('Дополнительные CUDA-зависимости не устанавливались.')"),
('### 3. Только distill checkpoint и shared компоненты\n\nНе вызываем download_models.py без --models: он скачивает несколько моделей. Наш downloader фильтрует компоненты и фиксирует revisions. Shared weights не уменьшаются от перехода SFT→distill.', "DOWNLOAD_WEIGHTS=False\nif DOWNLOAD_WEIGHTS:\n    from labkit.components import download_component\n    for name in ['qwen','clip','dit','vae']: print(name,download_component(name))\nelse: print('Скачивание весов пропущено.')"),
('### 4. Конфигурация с абсолютными путями\n\nВ официальный YAML вносим только пути к выбранным файлам. Hunyuan build_vae сам добавляет subfolder=vae, поэтому checkpoint_path указывает на корень weights/vae. Текстовые checkpoint_path указывают непосредственно на dirs qwen/clip.', "from omegaconf import OmegaConf\nconf=OmegaConf.load(SOURCE/'configs/k5_lite_t2v_5s_distil_sd.yaml')\nconf.model.checkpoint_path=str(ROOT/'weights/dit/model/kandinsky5lite_t2v_distilled16steps_5s.safetensors')\nconf.model.vae.checkpoint_path=str(ROOT/'weights/vae')\nconf.model.text_embedder.qwen.checkpoint_path=str(ROOT/'weights/qwen')\nconf.model.text_embedder.clip.checkpoint_path=str(ROOT/'weights/clip')\nconfig_path=ROOT/'artifacts/colab_distill.yaml'\nOmegaConf.save(conf,config_path)\nprint(OmegaConf.to_yaml(conf))"),
('### 5. Как создавать pipeline в этой версии\n\nУ pinned revision exported factory называется get_video_pipeline(mode="t2v"). README upstream показывает get_T2V_pipeline, но в текущем __init__.py такого alias нет. Поэтому используем функцию, реально существующую в сохранённом коде. SDPA выбран явно, MagCache выключен для чистого baseline.', "RUN_PIPELINE=False\nif RUN_PIPELINE:\n    assert torch.cuda.is_available(),'Нужен CUDA GPU'\n    assert torch.cuda.is_bf16_supported(),'Этот official BF16 путь не предназначен для T4'\n    if str(SOURCE) not in sys.path: sys.path.insert(0,str(SOURCE))\n    from kandinsky import get_video_pipeline\n    pipe=get_video_pipeline(device_map={'dit':torch.device('cuda:0'),'vae':torch.device('cuda:0'),'text_embedder':torch.device('cpu')},conf_path=str(config_path),offload=True,attention_engine='sdpa',text_token_padding=True,quantized_qwen=False,magcache=False,mode='t2v')\nelse: print('Официальный pipeline не создавался.')"),
('### 6. Полная генерация и измерение\n\nПеред каждым запуском переместим энкодеры на CPU: с offload официальный pipeline в конце может вернуть их на configured text device. seed/steps/guidance/scale задаём явно. Первый замер включает часть подготовки и compile; второй после прогрева сравним отдельно. Вызов сохраняет 5s видео и tensor результата.', "RUN_GENERATION=False\nif RUN_GENERATION:\n    assert RUN_PIPELINE,'Сначала создайте pipeline'\n    import time\n    from labkit.common import save_json\n    prompt='A cat in a red hat slowly turns its head. Static camera, warm daylight.'\n    pipe.text_embedder.to('cpu')\n    torch.cuda.reset_peak_memory_stats(); torch.cuda.synchronize(); start=time.perf_counter()\n    images=pipe(text=prompt,time_length=5,width=768,height=512,seed=42,num_steps=16,guidance_weight=1.,scheduler_scale=5.,expand_prompts=False,save_path=str(ROOT/'artifacts/colab_distill_5s.mp4'))\n    torch.cuda.synchronize(); elapsed=time.perf_counter()-start\n    report={'elapsed_seconds':elapsed,'peak_allocated_GiB':torch.cuda.max_memory_allocated()/2**30,'GPU':torch.cuda.get_device_name(0),'seed':42,'steps':16,'NFE':16,'scale':5.,'guidance':1.,'prompt':prompt,'source_revision':REVISION}\n    save_json(ROOT/'artifacts/colab_distill_5s.json',report); print(report)\n    from IPython.display import Video,display\n    display(Video(str(ROOT/'artifacts/colab_distill_5s.mp4'),embed=True))\nelse: print('Полная CUDA генерация НЕ выполнялась.')"),
('### 7. Если памяти не хватает\n\nQwen на CPU экономит VRAM, но требует RAM Colab и может быть медленным. На сервере с CUDA можно исследовать NF4 Qwen отдельно; это дополнительная зависимость bitsandbytes и отдельный эксперимент. 16 steps снижает вычисления, но число latent tokens сохраняется. Не скрывайте OOM автоматической заменой checkpoint.', "from labkit.common import device_info\nprint(device_info())\nprint('CPU Qwen BF16 ~13 GiB только округлённые веса; загрузка и hidden states требуют запас.')"),
('### Задания\n\n1. Сохраните замеры cold/warm launch отдельно.\n2. Сравните text encoder CPU/GPU при одинаковой VRAM и prompt.\n3. Проверьте число кадров и fps сохранённого MP4.\n4. Скачайте artifacts до закрытия runtime; локальные данные Colab временные.')])

write('11_kvae_separate.ipynb','11. KVAE: отдельный визуальный tokenizer','KVAE существует в Kandinsky Lab, но выбранный T2V distill checkpoint использует HunyuanVideo VAE. Совпадение 16 каналов и compression 4×8×8 не делает разные латентные пространства совместимыми.',[
('### 1. Два смысла слова tokenizer\n\nQwen tokenizer выдаёт дискретные номера подслов. KVAE visual tokenizer выдаёт непрерывный тензор latent. Здесь речь о втором. KVAE-Image 1.0 использует spatial 8×8, KVAE-Video 1.0 — temporal/spatial 4×8×8.', "import json\nfor model in ['KVAE-2D-1.0','KVAE-3D-1.0']:\n    path=ROOT/'reference/hf'/('kandinskylab--'+model)/'metadata.json'\n    metadata=json.loads(path.read_text())\n    print(model,'revision:',metadata['sha'])\n    print('files:',[x['rfilename'] for x in metadata['siblings'] if x['rfilename'].endswith(('.json','.safetensors','.py'))])"),
('### 2. Почему shape compatibility недостаточно\n\nДва энкодера могут одинаково сжимать изображение, но кодировать смысл разными координатами. Даже перестановка каналов ломает старый decoder. Маленькая линейная аналогия показывает этот эффект.', "image=torch.tensor([1.,2.,3.]); encoder=torch.eye(3); decoder=torch.eye(3)\npermutation=torch.tensor([[0.,1.,0.],[0.,0.,1.],[1.,0.,0.]])\nz1=encoder@image; z2=permutation@image\nprint('correct:',decoder@z1,'wrong decoder:',decoder@z2,'matched decoder:',permutation.T@z2)"),
('### 3. Что сообщает настоящая конфигурация\n\nУ KVAE encoder/decoder задают ch=128, z_channels=16 и temporal_compress_times=4. Causal блоки используют caches при сегментированной обработке. Нельзя чередовать независимые видео на одном instance: состояния относятся к одному stream.', "cfg=json.loads((ROOT/'reference/hf/kandinskylab--KVAE-3D-1.0/config.json').read_text())\nprint(json.dumps(cfg,indent=2,ensure_ascii=False))"),
('### 4. Настоящие классы KVAE без больших весов\n\nPinned KVAE source уже сохранён в reference/kvae. Загружаем только video/image modules в отдельном namespace: audio stack не импортируется. Создадим уменьшенный KVAEVideo с теми же CachedEncoder3D/CachedDecoder3D. Веса случайные: исследуем формы и segmented caches, не качество.', "from labkit.kvae import load_kvae_classes\nKVAEVideo,KVAEImage=load_kvae_classes()\nsmall_cfg={'model':{'encoder_params':{'ch':32,'ch_mult':[1,1,1,1],'num_res_blocks':1,'z_channels':4,'temporal_compress_times':4},'decoder_params':{'ch':32,'ch_mult':[1,1,1,1],'num_res_blocks':1,'z_channels':4,'temporal_compress_times':4}}}\nsmall=KVAEVideo(small_cfg).eval()\nvideo=torch.randn(1,3,9,32,32)\nwith torch.no_grad():\n    latent=small.encode(video,seg_len=8).latent_dist.mode()\n    restored=small.decode(latent,seg_len=8)\nprint('small KVAE:',video.shape,'→',latent.shape,'→',restored.shape)\nprint('parameters:',sum(p.numel() for p in small.parameters()))\ndel small; release()"),
('### 5. Mode reconstruction с настоящими весами\n\nСинтетическое видео движущегося квадрата позволяет увидеть temporal artifacts. Encode возвращает posterior; decode KVAE возвращает tensor, не DecoderOutput.sample. PSNR считаем на [0,1]. Здесь sample_mode выключает стохастический шум posterior.', "RUN_KVAE=False\nif RUN_KVAE:\n    from labkit.kvae import load_kvae_classes\n    KVAEVideo,KVAEImage=load_kvae_classes()\n    from labkit.components import REVISIONS\n    device='cuda' if torch.cuda.is_available() else 'cpu'\n    dtype=torch.bfloat16 if device=='cuda' else torch.float32\n    from huggingface_hub import snapshot_download\n    repo='kandinskylab/KVAE-3D-1.0'\n    checkpoint=snapshot_download(repo,revision=REVISIONS[repo],allow_patterns=['*.json','*.safetensors','*.bin'])\n    model=KVAEVideo.from_pretrained(checkpoint).eval().to(device=device,dtype=dtype)\n    video=torch.full((1,3,9,64,64),-1.,device=device,dtype=dtype)\n    for t in range(9): video[:,:,t,20:40,5+t*3:21+t*3]=1\n    with torch.no_grad():\n        latent=model.encode(video,seg_len=16).latent_dist.mode()\n        reconstruction=model.decode(latent,seg_len=16).clip(-1,1)\n    print('latent:',latent.shape,'reconstruction:',reconstruction.shape)\n    mse=((reconstruction.float()-video.float())/2).square().mean().item()\n    print('PSNR:',-10*np.log10(max(mse,1e-12)))\n    plt.imshow(((reconstruction[0,:,4].float().cpu()+1)/2).permute(1,2,0)); plt.show()\n    del model; release()\nelse: print('Настоящая реконструкция KVAE НЕ выполнялась.')"),
('### Задания\n\n1. Сравните Hunyuan и KVAE reconstruction на одинаковом видео.\n2. Исследуйте seg_len и память, используя отдельный instance на независимый stream.\n3. Какие эксперименты нужны, прежде чем заменить VAE для pretrained DiT?\n4. KVAE-2.0 имеет другие варианты compression; не переносите показатели 1.0 автоматически.')])
print('Wrote',len(list((ROOT/'notebooks').glob('*.ipynb'))),'notebooks')

# Deeper theory chapters are rebuilt together with the course.
import runpy
runpy.run_path(str(ROOT/"scripts/deepen_labs.py"))

runpy.run_path(str(ROOT/"scripts/add_inference_example.py"))

runpy.run_path(str(ROOT/"scripts/add_colab_launch.py"))

runpy.run_path(str(ROOT/"scripts/extend_from_materials.py"))

runpy.run_path(str(ROOT/"scripts/build_generation_lab.py"))
